version: "3.8"
services:
  node:
    image: node:12
    environment:
      PORT_NODE: ${PORT_NODE}
    ports:
      - ${PORT_NODE}:8080
    volumes:
      - ./:/var/www/jmask
    working_dir: /var/www/jmask
