name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Using branch ${{ github.ref }} for repository ${{ github.repository }}.
        uses: actions/checkout@v6

      - name: Show Docker Compose version
        run: docker compose version

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Run lint
        run: make lint

      - name: Run typecheck
        run: make typecheck

      - name: Run build
        run: make build

  tests:
    needs: checks

    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Using branch ${{ github.ref }} for repository ${{ github.repository }}.
        uses: actions/checkout@v6

      - name: Show Docker Compose version
        run: docker compose version

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Run merged coverage
        run: make coverage

      - name: Upload merged coverage artifact
        uses: actions/upload-artifact@v7
        with:
          name: coverage-merged
          path: coverage/merged
